name: Run Playwright API Auto-Checks on CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 playwright-api-auto-checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
        image: jaktestowac/gad:latest
        ports:
            - 3000:3000
      
    steps:
     - name: Run Docker Container
       run: docker run -d --name myapp-container jaktestowac/gad
     - name: Checkout the repository
       uses: actions/checkout@v3
     - name: Install node
       uses: actions/setup-node@v3
       with:
         node-version: '18.x'
     - name: Install dependencies
       run: npm ci
     - name: Install Playwright Chromium Browser
       run: npx playwright install --with-deps chromium
     - name: Run API checks
       run: docker exec myapp-container npx playwright test
     - name: Archive tests results
       if: success() || failure()
       uses: actions/upload-artifact@v3
       with: 
         name: test-report
         path: |
           ./playwright-report/**/*.*
           ./test-results/**/*.*
